### ISSUE TITLE
plan

### ISSUE THREAD

**Issue by matyaskopp** [matyaskopp/ufal#1]
### Sorted by priorities

- [x] [pml to sql conversion documentation](https://github.com/matyaskopp/ufal/blob/master/documentation/pml-tq/pml2sql.md)
- [x] New PML-TQ server installation
  -  [x] installation tutorial 
  -  [x] installation
      -  [x]  PMLTQ::Server
      -  [x]  Print Sever
      -  [x]  PMLTQ Web Frontend
      -  [x]  Database
  -  [x] [Customisable treebank help](https://github.com/ufal/perl-pmltq-web/issues/68)  
  -  [x] [add better user privileges management](https://github.com/ufal/perl-pmltq-server/issues/19) 
      - for each user set list of nonpublic treebank
      - what will happen i new treebank is added? (-> option `all_logged`)
- [x] Fix suggest: [perl-pmltq-web#39](https://github.com/ufal/perl-pmltq-web/issues/39),  [pmltq-print-server#1](https://github.com/ufal/pmltq-print-server/issues/1)
- [ ] History: [perl-pmltq-web#9](https://github.com/ufal/perl-pmltq-web/issues/9)
- [x] Bookmarks and query tutorial
  - [x] query manipulation
    - [x] delete query
    - [x] drop and down move query
    - [x] move query button
    - [x] copy query to button
    - [x] list of treebank's buttons (use query functionality)
  - [x] query and list manipulation
    - [x] edit description
    - [x] edit name
    - [x] save on focus lost
  - [x] tutorial
    - [x] add public query menu
      - [x] use query list
      - [x] view query list (tutorial)
    - [x] markdown editor for description
  - [x] euler deploy
  - [x] ldc deploy
- [x] fix treex schema bug (wrong encoding)
- [ ] LDC login https://github.com/ufal/perl-pmltq-server/issues/26
- [x] Fix query caching https://github.com/ufal/perl-pmltq-web/issues/65
- [x] Fix shuffled nodes in ptb extension
- [x] Fix node exploration https://github.com/ufal/perl-pmltq-web/issues/73
- [x] Fix permalink https://github.com/ufal/perl-pmltq-web/issues/75
- [ ] Easy PMLTQ Extension installation: [tred-extension-pmltq#1](https://github.com/ufal/tred-extension-pmltq/issues/1)
  - [ ] [documentation of instalation (tred, extension)](https://github.com/matyaskopp/ufal/blob/master/documentation/pml-tq/tred_extension_installation.md)
  - [ ] new TrEd release
    - [x] windows
    - [ ] mac
    - [x] linux deb
    - [x] linux rpm
    - [x] install_tred.bash
- [x] Recent https://github.com/ufal/perl-pmltq-server/issues/33 https://github.com/ufal/perl-pmltq-web/issues/81
- [ ] Euler performance tests
- [ ] Node inspection: [perl-pmltq-web#63](https://github.com/ufal/perl-pmltq-web/issues/63)
- [ ] Remove printserver from PMLTQ-Server: [tred-extension-pmltq#4](https://github.com/ufal/tred-extension-pmltq/issues/4)
   - it souldnt be easy because **suggest** is implemented within printserver
- [ ] Split PMLTQ to multiple distributions: [perl-pmltq#35](https://github.com/ufal/perl-pmltq/issues/35)
- [ ] Async database connection: [perl-pmltq#31](https://github.com/ufal/perl-pmltq/issues/31)
- [x] CLI client for PMLTQ: [perl-pmltq#32](https://github.com/ufal/perl-pmltq/issues/32)
- [ ] [Add ISWOC Treebanks to euler](https://github.com/ufal/perl-pmltq-web/issues/95)

**Comment by stranak** [comment]
On macOS 10.12.3 (current) I get this (after I first delete ~/.cpanm to solve permissions issue) when installing PML-TQ extension into the current TrEd.app:

```perl
"any" is not exported by the List::Util module
Can't continue after import errors at /Users/stranak/.tred.d/extensions/pmltq/contrib/pmltq/tree_query_http.mak line 38.
BEGIN failed--compilation aborted at /Users/stranak/.tred.d/extensions/pmltq/contrib/pmltq/tree_query_http.mak line 38.
```

**Comment by matyaskopp** [comment]
I think, that the problem is, that earlier versions of List::Util did not
export any. PMLTQ installs newer version, but it is not able to restart
TrEd. You must restart TrEd to load newly installed List::Util >v1.45.

Best
Matyáš

2017-02-06 15:50 GMT+01:00 Pavel Stranak <notifications@github.com>:
